name: Process Improvement Suggestion
description: Use this issue to suggest a new process improvement. 
title: 'Process Improvement Suggestion: ' 
labels: 'process suggestion'
body:
- type: markdown
  attributes: 
   value: "## Welcome!"
- type: dropdown
  attributes:
    label: Is your suggestion for a category, tool, or operational process improvement?
    multiple: true
    options:
      - Category
      - Tool
      - Operational Process
- type: checkboxes
  attributes:
    label: Please specifiy which category, tool, or operational process your suggestion involves: 
    options:
      - label: General Abuse
      - label: DMCA 
      - label: PIR 
      - label: Malicious Code 
      - label: npm Name Change Request 
      - label: Trade Compliance
      - label: Trademark 
      - label: Gov Takedown Requests 
      - label: User Care
      - label: COPPA 
      - label: Account Succession 
      - label: Reinstatement Requests
      - label: Escalations 
      - label: Triage 
      - label: Zendesk 
      - label: macros - create a [macro issue](https://github.com/github/trust-safety/issues/new?assignees=&labels=macro&template=macro-update-request.md&title=Macro+Request) for macro change requests) 
   
       
  
