name: Process Improvement Suggestion
description: Use this issue to suggest a new process improvement. 
title: 'Process Improvement Suggestion: ' 
labels: 'process suggestion'
body:
- type: markdown
  attributes: 
   value: "## Welcome!"
- type: dropdown
  attributes:
   label: Is your suggestion for a category, tool, or operational process improvement?
   multiple: true
   options:
    - Category
    - Tool
    - Operational Process
- type: checkboxes
  label: Blah Blah Blah 
  options:
  - label: example 1 
   - label: example 2 
