name: Process Improvement Suggestion
description: Use this issue to suggest a new process improvement. 
title: 'Process Improvement Suggestion: ' 
labels: 'process suggestion'
body:
  
  - type: markdown
    attributes:
      value: |
        Please use this form to tell us about your suggestion!
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
     
